# -*- coding: utf-8 -*-
"""fashion_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvpvqYp-6dHvHoP_ihPm35ETYfG7HsIG

# **import libraries and load the data set**
"""

import numpy as np
import tensorflow as tf
import tensorflow_datasets as fashion_mnist
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from warnings import filterwarnings
filterwarnings('ignore')

# Load the Fashion MNIST dataset
# Train
train_fashion_mnist = fashion_mnist.as_numpy(fashion_mnist.load("fashion_mnist", split="train", batch_size=-1))
X_train, y_train = train_fashion_mnist["image"], train_fashion_mnist["label"]
# Test
test_fashion_mnist = fashion_mnist.as_numpy(fashion_mnist.load("fashion_mnist", split="test", batch_size=-1))
X_test, y_test = test_fashion_mnist["image"], test_fashion_mnist["label"]

# Print the number of training and test samples
print("Train Samples:", len(X_train))
print("Test Samples:", len(X_test))
# Define fashion classes
fashion_classes = {0: 'T-shirt/top',
                   1: 'Trouser',
                   2: 'Pullover',
                   3: 'Dress',
                   4: 'Coat',
                   5: 'Sandal',
                   6: 'Shirt',
                   7: 'Sneaker',
                   8: 'Bag',
                   9: 'Ankle boot'}

"""# **Data Preprocessing**"""

# Check for any missing values in the dataset
if np.any(np.isnan(X_train)) or np.any(np.isnan(y_train)):
    print("Found missing values in training data.")
if np.any(np.isnan(X_test)) or np.any(np.isnan(y_test)):
    print("Found missing values in testing data.")

# Define the options for data augmentation
datagen = ImageDataGenerator(
    rotation_range=10,         # Randomly rotate images within 10 degrees
    horizontal_flip=True,      # Randomly flip images horizontally
    fill_mode='nearest'        # Fill new pixels with the nearest pixel values
)

# Function to preprocess data
def preprocess_data(images, use_augmentation=False):
    X = []
    for x_ in images:
        # Scale pixel values between 0.0-1.0
        x_ = x_ / 255.0
        # Data augmentation without increasing the number of images
        if use_augmentation:
            x_ = next(datagen.flow(x_.reshape(1, 28, 28, 1), batch_size=1))[0]
        X.append(x_)
    return np.array(X)

# Visualizing 5 random images
num_images = 5
indices = np.random.randint(len(X_train), size=num_images)
# Create a figure with subplots
fig, axes = plt.subplots(1, num_images, figsize=(15, 5))
for ax, idx in zip(axes, indices):
    ax.imshow(np.squeeze(X_train[idx]), cmap='gray')
    ax.axis('off')  # Turn off axis
    ax.set_title(f"Target: {fashion_classes[y_train[idx]]}")

plt.tight_layout()
plt.show()

# Preprocess training and test data
X_train_shaped = preprocess_data(X_train, use_augmentation=True).reshape((X_train.shape[0], 28, 28, 1))
X_test_shaped = preprocess_data(X_test).reshape((X_test.shape[0], 28, 28, 1))
# One-hot encode labels
y_train_shaped = tf.keras.utils.to_categorical(y_train)
y_test_shaped = tf.keras.utils.to_categorical(y_test)

# Flatten the training and test data for traditional classifiers
X_train_flat = X_train_shaped.reshape((X_train_shaped.shape[0], 28 * 28))
X_test_flat = X_test_shaped.reshape((X_test_shaped.shape[0], 28 * 28))

# Split data for training and validation
X_train_, X_val_, y_train_, y_val_ = train_test_split(X_train_shaped, y_train_shaped, test_size=0.2, random_state=42)
X_train_flat_, X_val_flat_, y_train_flat_, y_val_flat_ = train_test_split(X_train_flat, y_train_shaped, test_size=0.2, random_state=42)

"""# Bulid CNN Model and tray different epoche and plot **results**"""

# Import the necessary layers from Keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer, BatchNormalization, Conv2D, MaxPooling2D, Dropout, Flatten, Dense
# Building a CNN model
cnn = Sequential()
cnn.add(InputLayer(input_shape=(28, 28, 1)))  # Input layer

# Normalization
cnn.add(BatchNormalization())

# Conv + Maxpooling
cnn.add(Conv2D(64, (3, 3), padding='same', activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2, 2)))

# Dropout
cnn.add(Dropout(0.1))

# Conv + Maxpooling
cnn.add(Conv2D(64, (3, 3), activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2, 2)))

# Dropout
cnn.add(Dropout(0.3))

# Converting 3D feature to 1D feature vector
cnn.add(Flatten())

# Fully Connected Layer
cnn.add(Dense(256, activation='relu'))

# Dropout
cnn.add(Dropout(0.5))

# Fully Connected Layer
cnn.add(Dense(64, activation='relu'))

# Normalization
cnn.add(BatchNormalization())

# Output Layer
cnn.add(Dense(10, activation='softmax'))

# Compile the CNN model
cnn.compile(loss='categorical_crossentropy', optimizer=tf.optimizers.Adam(), metrics=['accuracy'])

# Print the model summary
cnn.summary()

"""# Model: Sequential
# Summary of each layer in the CNN model architecture:

# 1. Batch Normalization:
#    - Normalizes input data (shape: 28x28 with 1 channel) to stabilize training.
#    - Parameters: 4

# 2. Conv2D (Convolutional Layer):
#    - A convolutional layer with 64 filters of size 3x3.
#    - Output shape: 28x28 with 64 channels.
#    - Parameters: 640

# 3. Max Pooling 2D:
#    - Reduces spatial dimensions to 14x14, preserving depth.
#    - Parameters: 0

# 4. Dropout:
#    - Randomly disables some connections to reduce overfitting.
#    - Parameters: 0

# 5. Conv2D (Second Convolutional Layer):
#    - Another convolutional layer with 64 filters of size 3x3.
#    - Output shape: 12x12 with 64 channels.
#    - Parameters: 36,928

# 6. Max Pooling 2D (Second Max Pooling):
#    - Further reduces dimensions to 6x6, maintaining depth.
#    - Parameters: 0

# 7. Dropout:
#    - Second dropout layer for regularization.
#    - Parameters: 0

# 8. Flatten:
#    - Flattens the 3D input to a 1D vector (2304 units).
#    - Parameters: 0

# 9. Dense:
#    - A dense (fully connected) layer with 256 units.
#    - Parameters: 590,080

# 10. Dropout:
#    - Third dropout layer to prevent overfitting.
#    - Parameters: 0

# 11. Dense:
#    - Dense layer with 64 units.
#    - Parameters: 16,448

# 12. Batch Normalization:
#    - Normalizes output from the previous layer.
#    - Parameters: 256

# 13. Dense (Output Layer):
#    - Final dense layer with 10 units (one for each class).
#    - Parameters: 650

# Total Parameters: 645,006 (2.46 MB)
# - Trainable Parameters: 644,876 (2.46 MB)
# - Non-trainable Parameters: 130 (520.00 B)

"""

# Train the CNN model using augmented data 10 epochs
cnn_history = cnn.fit(
    X_train_, y_train_,
    batch_size=250,
    epochs=10,
    verbose=1,
    validation_data=(X_val_, y_val_),
)

# Try more epochs 20
cnn_history3 = cnn.fit(
    X_train_, y_train_,
    batch_size=250,
    epochs=20,
    verbose=1,
    validation_data=(X_val_, y_val_)
)

# Plotting accuracy and loss curves for the CNN model
import matplotlib.pyplot as plt

def plot_history(history, title):
    plt.figure(figsize=(8, 5))

    # plot accuracy
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Training Accuracy')
    plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
    plt.title(f'{title} - Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()

    # plot loss
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Training Loss')
    plt.plot(history.history['val_loss'], label='Validation Loss')
    plt.title(f'{title} - Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()

    plt.tight_layout()
    plt.show()

# Call the function for each model to illustrate the results of each configuration
plot_history(cnn_history, 'CNN - 10 Epochs')
plot_history(cnn_history2, 'CNN - 15 Epochs')
plot_history(cnn_history3, 'CNN - 20 Epochs')

"""# Adversarial examples in the physical

"""

import tensorflow as tf
import numpy as np
!pip install cleverhans
from cleverhans.tf2.attacks.fast_gradient_method import fast_gradient_method
import matplotlib.pyplot as plt

# Craft adversarial examples using FGSM
def craft_adversarial_examples(model, X_test, epsilon):
    return fast_gradient_method(model_fn=model, x=X_test, eps=epsilon, norm=np.inf)

# Evaluate the model and visualize results
def evaluate_and_visualize(model, X_test, y_test, epsilon):
    # Accuracy on clean data
    clean_acc = model.evaluate(X_test, y_test, verbose=0)[1]
    print(f"Accuracy on clean data: {clean_acc * 100:.2f}%")

    # Generate adversarial examples
    X_adv = craft_adversarial_examples(model, X_test, epsilon)
    adv_acc = model.evaluate(X_adv, y_test, verbose=0)[1]
    print(f"Accuracy on adversarial data (epsilon={epsilon}): {adv_acc * 100:.2f}%")

    # Visualize original and adversarial images
    indices = np.random.choice(len(X_adv), 5, replace=False)
    fig, axes = plt.subplots(2, 5, figsize=(15, 6))

    for i, idx in enumerate(indices):
        # Original images
        axes[0, i].imshow(np.squeeze(X_test[idx]), cmap='gray')
        axes[0, i].set_title(f"Original: {np.argmax(y_test[idx])}")
        axes[0, i].axis('off')

        # Adversarial images
        axes[1, i].imshow(np.squeeze(X_adv[idx]), cmap='gray')
        axes[1, i].set_title(f"Adversarial: {np.argmax(model.predict(X_adv[idx:idx+1]))}")
        axes[1, i].axis('off')

    plt.tight_layout()
    plt.show()

# Execute the adversarial attack
epsilon = 0.05
evaluate_and_visualize(cnn, X_test_shaped, y_test_shaped, epsilon)